# fly.toml app configuration file for stock-notifier-consumer
app = 'stock-notifier-consumer'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile.consumer'

[env]
  PYTHON_ENV = 'production'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate" 